services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch6
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - staccato-network

  staccato:
    build:
      context: ./staccato
      dockerfile: Dockerfile
    container_name: staccato-app
    depends_on:
      - elasticsearch
    environment:
      - STACCATO_ES_HOST=elasticsearch6
      - STACCATO_ES_PORT=9200
    ports:
      - "8080:8080"
    networks:
      - staccato-network

networks:
  staccato-network:
    driver: bridge