name: Docker Compose Build and Test Actuator endpoint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and Run Docker Compose
      - name: Build and Run Docker Compose
        run: |
          docker-compose down --volumes || true
          docker-compose up --build -d

      # Step 4: Wait for Services to Start
      - name: Wait for Actuator Endpoint to Become Ready
        run: |
          for i in {1..50}; do
            if curl --silent --fail http://localhost:8080/actuator/health; then
              echo "Actuator is up!"
              exit 0
            fi
            echo "Waiting for Actuator endpoint... ($i/10)"
            sleep 5
          done
          echo "Actuator endpoint did not become ready in time."
          exit 1

      # Step 5: Test Actuator Endpoint
      - name: Test Actuator Endpoint
        run: |
          response=$(curl --silent http://localhost:8080/actuator/health)
          echo "Response: $response"
          if echo "$response" | grep -q '"status":"UP"'; then
            echo "Actuator endpoint test passed."
          else
            echo "Actuator endpoint test failed."
            exit 1
          fi

      # Step 6: Tear Down Docker Compose
      - name: Tear Down Docker Compose
        if: always()
        run: |
          docker-compose down --volumes